const CHANGE_STATION = 'CHANGE_STATION'
const CHANGE_CHOOSE_INFO = 'CHANGE_CHOOSE_INFO'
const RESET_STATION = 'RESET_STATION'

export default {
  CHANGE_STATION,
  CHANGE_CHOOSE_INFO,
  RESET_STATION
}